# Generated by Django 4.0.5 on 2022-11-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_authoruser_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Кометарий', 'verbose_name_plural': 'Коментарии'},
        ),
    ]
